[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.25"
prost = "0.11.0"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.8.2"
rand = "0.8.5"

[build-dependencies]
tonic-build = "0.8.2"